"""Recovering an approval whose write was refused — without asking anyone to approve again.

THE PRODUCTION STATE (2026-09-17, `UTSW_Discharge_Summary.docx`). A 1.4.5 row sat `approved`
with `applied` NULL. The writer job had run and finished `done`, having refused the picture on
a crop safety check; the approved OCR transcript was kept, as the decision line promises. The
reviewer's card then told them:

    Approved, application pending. No active writer job is recorded; another approval is not
    needed.

Both halves of which misled. A job WAS recorded — it ran, and it refused for a stated reason
that was sitting in the decision log. And with no way to ask for the write again, "another
approval is not needed" left the only visible action being the one thing that would not help.

TWO THINGS ARE PINNED HERE, and they are the two halves of that dead end:

  * `automatic_review_queue.stalled_reason` now prefers the row's own `apply_outcome` — the
    refusal reason `store.list_hitl_queue` already parses onto it — so the card says what
    happened and what to do. This text reaches the user verbatim.
  * `store.retry_approved_write` re-runs the writer over content that is ALREADY approved. It
    creates no approval, records no decision on the row, clears nothing, marks nothing applied
    or verified, and enqueues exactly the payload a reviewer's own approval enqueues — so every
    downstream guard runs unchanged and a genuine refusal refuses again.

The value in this scan came from OCR, not a model (`ai_calls` was empty for that run), so
nothing asserted here may describe it as AI-generated.
"""
from __future__ import annotations

import json

import pytest

from apply_outcome import COULD_NOT_VERIFY, NOTHING_WRITTEN, STILL_FAILING
from automatic_review_queue import stalled_reason

CROP_REASON = ('The image is cropped in Word. Review a transcription of the visible crop and '
               'confirm no useful diagram content would be lost before replacing it. The '
               'original image is kept unchanged.')

SID = 'recovery-scan'
FILE = 'UTSW_Discharge_Summary.docx'


# ── the sentence the user reads ───────────────────────────────────────────────────────────

def test_a_refused_write_explains_itself_instead_of_denying_the_job_existed():
    row = {'status': 'approved', 'applied': None, 'rule_id': '1.4.5',
           'apply_outcome': {'outcome': NOTHING_WRITTEN, 'criteria': ['1.4.5'],
                             'reason': CROP_REASON}}
    reason = stalled_reason(row)
    # The refusal's own words reach the user, unaltered.
    assert CROP_REASON in reason
    # The two false/dead-end claims are gone.
    assert 'No active writer job is recorded' not in reason
    assert 'application pending' not in reason
    # And the user is told the approval survives and what to do next.
    assert 'approval still stands' in reason
    assert 'retry saving it' in reason
    assert 'not be asked to approve it again' in reason


def test_no_reason_string_claims_the_value_came_from_ai():
    """`ai_calls` was empty for this run: the transcript is OCR. Nothing may say otherwise."""
    outcomes = [{'outcome': NOTHING_WRITTEN, 'reason': CROP_REASON},
                {'outcome': COULD_NOT_VERIFY, 'reason': 'scan status error'},
                {'outcome': STILL_FAILING, 'reason': ''}, {}]
    for outcome in outcomes:
        for applied in (None, 1):
            text = stalled_reason({'status': 'approved', 'applied': applied,
                                   'apply_outcome': outcome}).lower()
            assert not any(word in text for word in
                           (' ai ', 'ai-', 'artificial intelligence', 'model-written',
                            'generated by', 'ai suggestion')), text


def test_a_written_but_unverified_change_is_not_described_as_unsaved():
    reason = stalled_reason({'status': 'approved', 'applied': None,
                             'apply_outcome': {'outcome': COULD_NOT_VERIFY,
                                               'reason': "scan status 'error', 1 rule(s) skipped"}})
    assert 'was written' in reason
    assert 'no further approval is needed' in reason
    assert "scan status 'error'" in reason


def test_the_fallback_no_longer_claims_no_job_was_ever_recorded():
    """The honest weaker claim: none is running NOW — true whether one finished or none existed."""
    unsaved = stalled_reason({'status': 'approved', 'applied': None})
    saved = stalled_reason({'status': 'approved', 'applied': 1})
    for text in (unsaved, saved):
        assert 'is recorded' not in text
        assert 'running right now' in text
        assert 'Another approval is not needed.' in text
    assert 'not yet saved into the document' in unsaved
    assert 'not yet independently checked' in saved


# ── the retry that creates no approval ────────────────────────────────────────────────────

@pytest.fixture
def store(monkeypatch, tmp_path):
    import store as store_module
    monkeypatch.setattr(store_module, '_SQLITE_PATH', tmp_path / 'recovery.db')
    return store_module.Store()


def seed(store, *, status='approved', value='Discharge instructions'):
    """The production shape: one 1.4.5 proposal, approved, `applied` never set."""
    store.init_scan_run(SID, 'drive', 1, '2026-09-17T00:00:00Z', 'rubric', 'hash')
    store.save_file_result(SID, {
        'file': FILE, 'engine': 'office', 'status': 'pass', 'score': 60, 'compliant': 0,
        'skipped_rules': 0, 'drive_file_id': 'd1',
        'issues': [{'ruleId': 'OCR_IMAGE_OF_TEXT', 'wcag': '1.4.5 Images of Text',
                    'severity': 'SERIOUS', 'detail': 'embedded image 1 contains readable text'}],
    }, '2026-09-17T00:00:00Z')
    store.record_remediation(SID, FILE, drive_write_url='http://d/1', blob_url='http://b/1', corrected_sha256='a'*64)
    item_id = store.enqueue_proposals(SID, FILE, '1.4.5', [
        {'locator': 'image 1', 'before': 'text baked into an image', 'proposed_value': value,
         'rationale': 'r', 'source': 'OCR'}], rule_name='Images of Text')
    with store._db.cursor() as cur:
        store._db.execute(cur, 'UPDATE hitl_queue SET proposal_snapshot_ids=%s WHERE id=%s',
                          (json.dumps(['immutable-proposal-1']), item_id))
    if status:
        # The production decision path, so the approval's OWN writer enqueue, decision-log line
        # and value binding are all real — a retry that only ever ran against a hand-built row
        # would prove nothing about the state this recovers.
        store.complete_hitl_decision(item_id, status, None, None, resolution=None,
                                     approved_values=[value] if status == 'approved' else None,
                                     actor='reviewer@example.com', detail=None)
    return item_id


def writer_jobs(store):
    with store._db.cursor() as cur:
        store._db.execute(cur, "SELECT id,type,payload,status FROM jobs "
                               "WHERE scan_id=%s AND type='apply_approved_values'", (SID,))
        return store._db.fetchall(cur)


def snapshot(store, item_id):
    """Everything about the row a recovery must not touch."""
    row = store.get_hitl_item(item_id)
    return {k: row.get(k) for k in (
        'status', 'applied', 'validated', 'decision_version', 'approved_value_sha256',
        'approved_source_revision', 'approved_proposal_snapshot_ids', 'reviewed_at',
        'last_decision_request_id', 'proposals', 'resolution', 'reviewer_note')}


def test_retry_enqueues_the_writer_and_creates_no_approval(store):
    item_id = seed(store)
    # The approval's own enqueue has already happened and (in production) already refused; drop
    # it so the state under test is the stranded one: approved, unapplied, nothing in flight.
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE jobs SET status='done' WHERE scan_id=%s", (SID,))
    before = snapshot(store, item_id)
    decisions_before = {d['id'] for d in store.list_decisions(scan_id=SID)}

    result = store.retry_approved_write(item_id, actor='reviewer@example.com')

    assert result['accepted'] is True and result['existing'] is False and result['reason'] is None
    queued = [j for j in writer_jobs(store) if j['status'] == 'queued']
    assert len(queued) == 1 and queued[0]['id'] == result['job_id']
    # The SAME payload a reviewer's own approval enqueues: the handler, and therefore every
    # downstream guard, runs unchanged.
    payload = json.loads(queued[0]['payload']) if isinstance(queued[0]['payload'], str) else queued[0]['payload']
    assert payload['scan_id'] == SID and payload['file'] == FILE
    assert payload['item_id'] == item_id
    assert payload['approved_binding'] == store.approved_write_binding(store.get_hitl_item(item_id))[0]

    # NOTHING about the review row moved. No new approval, no decision_version bump, not applied.
    assert snapshot(store, item_id) == before
    assert store.get_hitl_item(item_id)['status'] == 'approved'
    assert not store.get_hitl_item(item_id).get('applied')
    assert store.count_unapplied_approved_values(SID, FILE) > 0
    # EXACTLY ONE new audit line, and it is not a decision on the item: the `hitl.approved`
    # line belongs to the reviewer's original approval and no second one may appear.
    added = [d for d in store.list_decisions(scan_id=SID) if d['id'] not in decisions_before]
    assert [d['action'] for d in added] == ['apply.retry_requested']
    assert added[0]['actor'] == 'reviewer@example.com'
    assert 'no new approval was created' in added[0]['detail']
    assert len([d for d in store.list_decisions(scan_id=SID)
                if d['action'].startswith('hitl.')]) == 1


def test_retry_is_idempotent_and_never_races_a_second_writer(store):
    item_id = seed(store)
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE jobs SET status='done' WHERE scan_id=%s", (SID,))
    first = store.retry_approved_write(item_id)
    second = store.retry_approved_write(item_id)
    third = store.retry_approved_write(item_id)
    assert second == {'accepted': True, 'in_flight': True, 'status': 'queued', 'job_id': first['job_id'], 'existing': True, 'reason': None}
    assert third['existing'] is True
    assert len([j for j in writer_jobs(store) if j['status'] == 'queued']) == 1


def test_a_writer_already_in_flight_is_the_retry(store):
    """The approval's own job is still queued: returning it beats racing it over the same bytes."""
    item_id = seed(store)
    live = [j for j in writer_jobs(store) if j['status'] == 'queued']
    assert len(live) == 1, 'the approval must have enqueued a writer to begin with'
    result = store.retry_approved_write(item_id)
    assert result == {'accepted': True, 'in_flight': True, 'status': 'queued', 'job_id': live[0]['id'], 'existing': True, 'reason': None}
    assert len(writer_jobs(store)) == 1


@pytest.mark.parametrize('status', ['pending', 'rejected', 'skipped'])
def test_retry_refuses_anything_that_is_not_an_approved_unapplied_row(store, status):
    item_id = seed(store, status=None)
    if status != 'pending':
        store.update_hitl_item(item_id, status, None, None)
    result = store.retry_approved_write(item_id)
    assert result['accepted'] is False
    assert result['reason'] == store.RETRY_NOT_APPROVED
    assert writer_jobs(store) == []


def test_retry_refuses_a_row_already_applied_rather_than_writing_twice(store):
    item_id = seed(store)
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE jobs SET status='done' WHERE scan_id=%s", (SID,))
        store._db.execute(cur, "UPDATE hitl_queue SET applied=1 WHERE id=%s", (item_id,))
    result = store.retry_approved_write(item_id)
    assert result['accepted'] is False and result['reason'] == store.RETRY_NOT_APPROVED
    assert [j for j in writer_jobs(store) if j['status'] == 'queued'] == []


def test_retry_refuses_when_the_document_moved_on_since_the_approval(store):
    """Identity and version are not negotiable — a retry may not write into a different source."""
    item_id = seed(store)
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE jobs SET status='done' WHERE scan_id=%s", (SID,))
        store._db.execute(cur,
            "UPDATE hitl_queue SET approved_source_revision='a-revision-that-is-not-current' "
            "WHERE id=%s", (item_id,))
    result = store.retry_approved_write(item_id)
    assert result['accepted'] is False and result['reason'] == store.RETRY_SOURCE_MOVED
    assert [j for j in writer_jobs(store) if j['status'] == 'queued'] == []


def test_retry_refuses_a_row_that_owes_the_document_no_content(store):
    item_id = seed(store)
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE jobs SET status='done' WHERE scan_id=%s", (SID,))
        # An approval carrying no writable locator: nothing for an applier to do.
        store._db.execute(cur, "UPDATE hitl_queue SET proposals=%s WHERE id=%s",
                          (json.dumps([{'locator': '', 'proposed_value': 'x',
                                        'approved_value': 'x'}]), item_id))
    result = store.retry_approved_write(item_id)
    assert result['accepted'] is False
    assert result['reason'] == store.RETRY_VALUES_CHANGED
    assert [j for j in writer_jobs(store) if j['status'] == 'queued'] == []


def test_retry_of_a_vanished_item_answers_rather_than_raising(store):
    result = store.retry_approved_write('no-such-item')
    assert result['accepted'] is False and 'no longer exists' in result['reason']


def test_the_refused_crop_row_recovers_end_to_end_once_the_writer_can_write(store, monkeypatch):
    """The whole point, joined up: refuse → explain → retry → write, with one approval throughout.

    The first apply run refuses (a genuine crop). The card then carries the refusal's own words.
    The retry re-runs the writer over the same approval — and when the obstacle is gone, the
    value lands, with no second approval and no decision recorded against the row.
    """
    import core
    import handlers
    import sys as _sys
    import test_remediation_verified_pptx_image_of_text as lane
    from test_image_of_text_writer_crop_geometry import placed
    from test_remediation_verified_office_image_replacement import members

    item_id = seed(store, value='Discharge instructions\nTake one tablet daily')
    approvals_before = store.get_hitl_item(item_id)['decision_version']
    cropped = placed({})
    blob = lane._Blob(cropped)
    monkeypatch.setattr(core, 'store', store)
    monkeypatch.setitem(_sys.modules, 'blob', blob)

    import apply_office_image_replacement as writer
    with monkeypatch.context() as old:
        old.setattr(writer, '_simple_picture', lambda *a, **kw: False)
        handlers._apply_approved_values({'scan_id': SID, 'file': FILE}, {})
    assert not blob.uploads and blob.data == cropped

    row = next(r for r in store.list_hitl_queue(scan_id=SID) if r['id'] == item_id)
    assert row['apply_outcome']['outcome'] == NOTHING_WRITTEN
    assert 'retry saving it' in stalled_reason(row)

    # The obstacle is removed the only honest way: the document no longer carries the crop.
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE jobs SET status='done' WHERE scan_id=%s", (SID,))
    import hashlib
    store.record_remediation(SID, FILE, corrected_sha256=hashlib.sha256(blob.data).hexdigest())
    assert store.retry_approved_write(item_id)['accepted'] is True
    queued = next(j for j in writer_jobs(store) if j['status'] == 'queued')
    handlers._apply_approved_values(json.loads(queued['payload']), {})

    assert blob.uploads, 'the retry must actually write'
    assert not any('/media/' in part for part in members(blob.data))
    assert store.count_unapplied_approved_values(SID, FILE) == 0
    # ONE approval, start to finish.
    assert store.get_hitl_item(item_id)['decision_version'] == approvals_before
    assert len([d for d in store.list_decisions(scan_id=SID)
                if d['action'].startswith('hitl.')]) == 1

@pytest.mark.parametrize('column,value,reason', [
    ('approved_source_revision', None, 'RETRY_NO_BINDING'),
    ('approved_value_sha256', None, 'RETRY_NO_BINDING'),
    ('decision_version', 0, 'RETRY_NO_BINDING'),
    ('approved_proposal_snapshot_ids', None, 'RETRY_NO_BINDING'),
    ('approved_proposal_snapshot_ids', '[null]', 'RETRY_NO_BINDING'),
    ('approved_proposal_snapshot_ids', '["replaced"]', 'RETRY_PROPOSALS_SUPERSEDED'),
])
def test_missing_or_changed_approval_binding_cannot_enqueue(store, column, value, reason):
    item_id = seed(store)
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE jobs SET status='done'")
        store._db.execute(cur, f'UPDATE hitl_queue SET {column}=%s WHERE id=%s', (value, item_id))
    result = store.retry_approved_write(item_id)
    assert not result['accepted'] and not result['in_flight']
    assert result['reason'] == getattr(store, reason)
    assert not [j for j in writer_jobs(store) if j['status'] == 'queued']


@pytest.mark.parametrize('status', ['done', 'dead', 'cancelled'])
def test_terminal_retry_does_not_claim_processing_or_enqueue_again(store, status):
    item_id = seed(store)
    with store._db.cursor() as cur: store._db.execute(cur, "UPDATE jobs SET status='done'")
    first = store.retry_approved_write(item_id)
    with store._db.cursor() as cur:
        store._db.execute(cur, 'UPDATE jobs SET status=%s WHERE id=%s', (status, first['job_id']))
    again = store.retry_approved_write(item_id)
    assert not again['accepted'] and not again['in_flight'] and again['status'] == status
    assert len(writer_jobs(store)) == 2


def test_worker_refuses_missing_binding_and_changes_after_admission(store, monkeypatch):
    import core, handlers
    monkeypatch.setattr(core, 'store', store)
    item_id = seed(store)
    with store._db.cursor() as cur: store._db.execute(cur, "UPDATE jobs SET status='done'")
    result = store.retry_approved_write(item_id)
    job = next(j for j in writer_jobs(store) if j['id'] == result['job_id'])
    payload = json.loads(job['payload'])
    with pytest.raises(handlers.FatalJobError):
        handlers._apply_approved_values({k:v for k,v in payload.items() if k != 'approved_binding'}, {})
    with store._db.cursor() as cur:
        store._db.execute(cur, 'UPDATE hitl_queue SET decision_version=decision_version+1 WHERE id=%s', (item_id,))
    with pytest.raises(handlers.FatalJobError): handlers._apply_approved_values(payload, {})


def test_worker_cannot_write_changed_blob(store, monkeypatch):
    import core, handlers, sys
    from types import SimpleNamespace
    monkeypatch.setattr(core, 'store', store)
    item_id = seed(store)
    with store._db.cursor() as cur: store._db.execute(cur, "UPDATE jobs SET status='done'")
    result = store.retry_approved_write(item_id)
    payload = json.loads(next(j for j in writer_jobs(store) if j['id'] == result['job_id'])['payload'])
    monkeypatch.setitem(sys.modules, 'blob', SimpleNamespace(download_remediated=lambda *a:b'other bytes'))
    with pytest.raises(handlers.FatalJobError, match='document has changed'):
        handlers._apply_approved_values(payload, {})


def test_scoped_retry_does_not_read_other_approved_values(store):
    item_id = seed(store)
    other = store.enqueue_proposals(SID, FILE, '1.1.1', [
        {'locator':'word/document.xml#rId42', 'proposed_value':'Other value'}])
    store.complete_hitl_decision(other, 'approved', None, None, approved_values=['Other value'], resolution=None, actor='reviewer', detail=None)
    assert store.approved_alt_values(SID, FILE)
    assert store.approved_alt_values(SID, FILE, item_id=item_id) == {}
    assert store.approved_images_of_text_values(SID, FILE, item_id=other) == {}


def test_retry_route_auth_owner_and_actual_response(store, monkeypatch):
    import core
    from app import app
    from fastapi.testclient import TestClient
    monkeypatch.setattr(core, 'store', store)
    monkeypatch.setattr(core, 'ACCESS_CODE', '')
    monkeypatch.setattr(core, 'GOOGLE_CLIENT_ID', 'test-client-id')
    monkeypatch.setattr(core, 'E2E_KEY', None)
    monkeypatch.setattr(core, 'OWNER_EMAIL', 'owner@example.com')
    monkeypatch.setattr(core, 'verify_gis_token', lambda t:t)
    monkeypatch.setattr(core, 'email_allowed', lambda e:True)
    item_id = seed(store)
    with store._db.cursor() as cur:
        store._db.execute(cur, "UPDATE scan_runs SET owner_email='owner@example.com' WHERE id=%s", (SID,))
    client = TestClient(app)
    url = f'/hitl/queue/{item_id}/retry-write'
    assert client.post(url).status_code == 401
    assert client.post(url, headers={'Authorization':'Bearer other@example.com'}).status_code == 404
    response = client.post(url, headers={'Authorization':'Bearer owner@example.com'})
    assert response.status_code == 200, response.text
    assert response.json()['accepted'] and response.json()['in_flight']
    assert response.json()['status'] == 'queued'
    assert store.get_hitl_item(item_id)['decision_version'] == 1


def test_concurrent_retries_for_two_rows_share_one_file_writer(store):
    from concurrent.futures import ThreadPoolExecutor
    first = seed(store)
    second = store.enqueue_proposals(SID, FILE, '1.1.1', [{'locator':'word/document.xml#rId1','proposed_value':'Description'}])
    with store._db.cursor() as cur:
        store._db.execute(cur, 'UPDATE hitl_queue SET proposal_snapshot_ids=%s WHERE id=%s', ('["snapshot-2"]',second))
    store.complete_hitl_decision(second, 'approved', None, None, approved_values=['Description'], resolution=None, actor='reviewer', detail=None)
    with store._db.cursor() as cur: store._db.execute(cur,"UPDATE jobs SET status='done'")
    with ThreadPoolExecutor(max_workers=2) as pool:
        outcomes = list(pool.map(store.retry_approved_write,[first,second]))
    assert sum(r['accepted'] for r in outcomes) == 1
    assert [r['reason'] for r in outcomes if not r['accepted']] == [store.RETRY_WRITER_BUSY]
    assert len([j for j in writer_jobs(store) if j['status']=='queued']) == 1


def test_retry_requires_review_permission_even_for_ones_own_scan(store, monkeypatch):
    import core, workspace_roles as roles, workspace_rollout as rollout
    from app import app
    from fastapi.testclient import TestClient
    owner, viewer = 'owner@example.com', 'viewer@example.com'
    monkeypatch.setattr(core, 'store', store)
    monkeypatch.setattr(core, 'ACCESS_CODE', '')
    monkeypatch.setattr(core, 'GOOGLE_CLIENT_ID', 'test-client-id')
    monkeypatch.setattr(core, 'E2E_KEY', None)
    monkeypatch.setattr(core, 'OWNER_EMAIL', owner)
    monkeypatch.setattr(core, 'OPEN_ACCESS', True)
    monkeypatch.setattr(core, 'verify_gis_token', lambda t:t)
    monkeypatch.setattr(core, 'email_allowed', lambda e:True)
    monkeypatch.setenv(rollout.MODE_VAR, 'enforce')
    roles.seed_builtin_roles(store, tenant_id=owner, actor=owner)
    store.upsert_person({'email':viewer,'workspace_role_id':'viewer','status':'access_ready'})
    item_id = seed(store)
    with store._db.cursor() as cur:
        store._db.execute(cur, 'UPDATE scan_runs SET owner_email=%s WHERE id=%s', (viewer,SID))
    before = writer_jobs(store)
    response = TestClient(app).post(f'/hitl/queue/{item_id}/retry-write', headers={'Authorization':f'Bearer {viewer}'})
    assert response.status_code == 403, response.text
    assert writer_jobs(store) == before
